### ISSUE TITLE
Redis 7.0 Support

### ISSUE THREAD

**Issue by chasain** [bitnami/bitnami-docker-redis-cluster#44]
### Name and Version

bitnami/redis-cluster

### What is the problem this feature will solve?

Support for sharded pub/subs

### What is the feature you are proposing to solve the problem?

Redis 7.0 now supports sharded pub/subs, supporting this version would be a major improvement

### What alternatives have you considered?

Using mainstream redis images and managing the cluster out of band

**Comment by javsalgar** [comment]
Hi,

Thanks for opening the issue. The team will work on the release of the new branch. As it is a major branch, it will take some time. As soon as there are news we will update this ticket.

**Comment by chasain** [comment]
Awesome, thanks for the update

**Comment by andres-voldman** [comment]
This is released now. 

are there plans to change the image to use hostnames instead of IPs?

**Comment by javsalgar** [comment]
Hi!

There are plans to improve the image, but I cannot guarantee an ETA. As contributions are welcome, would you like to submit a PR changing the logic to use hostnames?

**Comment by avcad** [comment]
Hi @javsalgar, Thanks.
I will take a look at the code and If I can figure it out, I will create a PR.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
