### ISSUE TITLE
Support docker swarm

### ISSUE THREAD

**Issue by 838239178** [bitnami/bitnami-docker-redis-cluster#48]
### Name and Version

bitnami/redis-cluster

### What is the problem this feature will solve?

Support docker swarm
How to deploy by docker stack

### What is the feature you are proposing to solve the problem?

Support docker swarm
How to deploy by docker stack

**Comment by carrodher** [comment]
Bitnami container images are tested using docker-compose and Helm (on top of different k8s clusters such as TKG, IKS, AKS, GKE, etc). In the case of Docker swarm is not officially supported since we are not testing the containers using this platform, this does not mean that it does not work, in fact, it is possible that any container works without problem, but since it is not tested it is something that we cannot guarantee or provide support

**Comment by 838239178** [comment]
How to use docker-compose to deploy to different nodes

**Comment by carrodher** [comment]
For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
