### ISSUE TITLE
No support for "tls-auth-clients no"

### ISSUE THREAD

**Issue by jpasquers** [bitnami/bitnami-docker-redis-cluster#5]
https://github.com/bitnami/bitnami-docker-redis-cluster/blob/93822c76a8375c094e2c659af26472b3ed9a7528/6.0/debian-10/rootfs/opt/bitnami/scripts/librediscluster.sh#L178

If you look here (and in multiple other spots), "tls-auth-clients" has 0 affect on the redis-cli commands. If you pass in a crt/key in a redis-cli command, even if the server has disabled auth-clients, it will attempt to validate the client certificate. If we disable auth-clients, these commands should not include the crt or key flags, but just the cacert. 

As a further note, the fact that there is no distinction between the client and server certificates is incredibly confusing. It appears that the same certs are used for the server certificate and client certificate.

**Comment by joancafom** [comment]
Hi @jpasquers,

Thanks for your issue! I believe this is has to do more with redis itself. According to their [documentation](https://redis.io/topics/encryption#client-certificate-authentication), by using `tls-auth-clients` it will disable client authentication, so we should not expect a verification even if certificates are present in the request. I think that is the logical approach 😄 followed. I saw you already created an [issue](https://github.com/antirez/redis/issues/7437) in the official repo and they seem to be fixing that 🎉.

Regarding the certificates usage, the approach here is that `redis-cli` re-uses the same server certificates in the set up and configuration stage (for example, when creating the cluster). This `redis-cli` instance runs within the redis server, and the client connecting in order to configure is the server itself. When connecting from the outside, a proper certificate identifying the client that is requesting a connection should be used.

Thanks!

**Comment by jpasquers** [comment]
Gotcha. Yea I think thats understandable since they are fixing it on their end. I guess my thought was that it couldn't hurt to filter out those flags, but as long as they fix it it should be okay. 

What prompted the second question is that the server certificate I'm using doesn't work as a client certificate (I'm frankly not sure why here, my knowledge of the difference there is a bit lacking). So I think that I just need to figure out why my certificate doesn't work as both.

Thanks for looking into this. Can close this
